<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model"
    nsURI="http://www.users.exa.unicen.edu.ar/~esolis/sadanalyzer" nsPrefix="edu.isistan.sadanalyzer.model">
  <eClassifiers xsi:type="ecore:EClass" name="Identifiable" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Nameable" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SadAnalyzerProject" eSuperTypes="#//Identifiable #//Nameable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sad" eType="ecore:EClass ../../edu.isistan.softwarearchitecturedocumentationanalyzer/model/sad.ecore#//Sad"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sadURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uimaURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CrosscuttingConcerns" upperBound="-1"
        eType="#//CrosscuttingConcern"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CrosscuttingConcern" eSuperTypes="#//Identifiable #//Nameable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Impacts" upperBound="-1"
        eType="#//Impact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sads" upperBound="-1" eType="ecore:EClass ../../edu.isistan.softwarearchitecturedocumentationanalyzer/model/sad.ecore#//Sad"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Impact" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Realization" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="section" eType="ecore:EClass ../../edu.isistan.softwarearchitecturedocumentationanalyzer/model/sad.ecore#//SadSection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sad" eType="ecore:EClass ../../edu.isistan.softwarearchitecturedocumentationanalyzer/model/sad.ecore#//Sad"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sentence" eType="ecore:EClass platform:/plugin/edu.isistan.uima.model/model/uima.ecore#//isistan/uima/unified/typesystems/nlp/Sentence"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CompositionRules" eType="#//CompositionRules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CompositionRules">
    <eLiterals name="Wrap"/>
    <eLiterals name="Overlap" value="1"/>
    <eLiterals name="Override" value="2"/>
  </eClassifiers>
</ecore:EPackage>
