<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model"
    nsURI="http://www.users.exa.unicen.edu.ar/~arago/ccdetector" nsPrefix="edu.isistan.reassistant.ccdetector">
  <eClassifiers xsi:type="ecore:EClass" name="CrosscuttingConcernRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Metadata" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CompositionGuidelines"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CompositionRule" eType="#//CompositionRule"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DirectQuerySet" eType="#//QuerySet"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ImpactQuerySet" eType="#//QuerySet"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Enabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CompositionRule">
    <eLiterals name="Wrap"/>
    <eLiterals name="Overlap" value="1"/>
    <eLiterals name="Override" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CrosscuttingConcernRuleSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Rules" upperBound="-1"
        eType="#//CrosscuttingConcernRule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="QueryPreference" eType="#//QueryPreference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QuerySet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Queries" upperBound="-1"
        eType="#//Query" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Query">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Include" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="QueryPreference">
    <eLiterals name="BothDirectAndImpact"/>
    <eLiterals name="OnlyDirect" value="1"/>
    <eLiterals name="OnlyImpact" value="2"/>
  </eClassifiers>
</ecore:EPackage>
